name: Run tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "25 22 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CARGO_INCREMENTAL: 0
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      CARGO_NET_RETRY: 10
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D warnings
      RUSTUP_MAX_RETRIES: 10
      ASAN_OPTIONS: detect_leaks=1

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, miri, rustfmt
          target: x86_64-unknown-linux-gnu
          toolchain: nightly

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy --all --all-targets

      - name: Check docs
        run: cargo doc --all

      - name: Run tests in relase mode
        run: cargo test --all --all-targets --release

      - name: Run tests with miri
        run: cargo miri test -p emplacable

      - name: Install cargo careful
        run: cargo install cargo-careful

      - name: Run tests with careful
        run: cargo careful test --all --all-targets -Zcareful-sanitizer
